# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_eav_model}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcus Wyatt"]
  s.date = %q{2010-11-17}
  s.description = %q{Entity-attribute-value model (EAV) is a data model that is used in circumstances 
    where the number of attributes (properties, parameters) that can be used to describe 
    a thing (an "entity" or "object") is potentially very vast, but the number that will 
    actually apply to a given entity is relatively modest.}
  s.email = %q{}
  s.extra_rdoc_files = [
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".rvmrc",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "SPECDOC",
    "TODO",
    "VERSION",
    "acts_as_eav_model.gemspec",
    "doc/classes/ActiveRecord/Acts/EavModel.html",
    "doc/classes/ActiveRecord/Acts/EavModel/ClassMethods.html",
    "doc/classes/ActiveRecord/Acts/EavModel/InstanceMethods.html",
    "doc/classes/ActiveRecord/Acts/EavModel/InstanceMethods/ClassMethods.html",
    "doc/classes/ActiveRecord/Base.html",
    "doc/created.rid",
    "doc/files/CHANGELOG.html",
    "doc/files/MIT-LICENSE.html",
    "doc/files/README_rdoc.html",
    "doc/files/SPECDOC.html",
    "doc/files/lib/acts_as_eav_model_rb.html",
    "doc/fr_class_index.html",
    "doc/fr_file_index.html",
    "doc/fr_method_index.html",
    "doc/index.html",
    "doc/rdoc-style.css",
    "init.rb",
    "install.rb",
    "lib/acts_as_eav_model.rb",
    "spec/dummy/Rakefile",
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/models/document.rb",
    "spec/dummy/app/models/person.rb",
    "spec/dummy/app/models/person_contact_info.rb",
    "spec/dummy/app/models/post.rb",
    "spec/dummy/app/models/post_attribute.rb",
    "spec/dummy/app/models/preference.rb",
    "spec/dummy/app/views/layouts/application.html.erb",
    "spec/dummy/config.ru",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/database.yml",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/locales/en.yml",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/development.sqlite3",
    "spec/dummy/db/schema.rb",
    "spec/dummy/public/404.html",
    "spec/dummy/public/422.html",
    "spec/dummy/public/500.html",
    "spec/dummy/public/favicon.ico",
    "spec/dummy/public/javascripts/application.js",
    "spec/dummy/public/javascripts/controls.js",
    "spec/dummy/public/javascripts/dragdrop.js",
    "spec/dummy/public/javascripts/effects.js",
    "spec/dummy/public/javascripts/prototype.js",
    "spec/dummy/public/javascripts/rails.js",
    "spec/dummy/public/stylesheets/.gitkeep",
    "spec/dummy/script/rails",
    "spec/fixtures/people.yml",
    "spec/fixtures/person_contact_infos.yml",
    "spec/fixtures/post_attributes.yml",
    "spec/fixtures/posts.yml",
    "spec/fixtures/preferences.yml",
    "spec/models/eav_model_with_no_arguments_spec.rb",
    "spec/models/eav_model_with_options_spec.rb",
    "spec/models/eav_validation_spec.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/g5search/acts_as_eav_model}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Entity Attribute Value Implementation for inclusion in ActiveRecord models.}
  s.test_files = [
    "spec/dummy/app/controllers/application_controller.rb",
    "spec/dummy/app/helpers/application_helper.rb",
    "spec/dummy/app/models/document.rb",
    "spec/dummy/app/models/person.rb",
    "spec/dummy/app/models/person_contact_info.rb",
    "spec/dummy/app/models/post.rb",
    "spec/dummy/app/models/post_attribute.rb",
    "spec/dummy/app/models/preference.rb",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/development.rb",
    "spec/dummy/config/environments/production.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/initializers/backtrace_silencers.rb",
    "spec/dummy/config/initializers/inflections.rb",
    "spec/dummy/config/initializers/mime_types.rb",
    "spec/dummy/config/initializers/secret_token.rb",
    "spec/dummy/config/initializers/session_store.rb",
    "spec/dummy/config/routes.rb",
    "spec/dummy/db/schema.rb",
    "spec/models/eav_model_with_no_arguments_spec.rb",
    "spec/models/eav_model_with_options_spec.rb",
    "spec/models/eav_validation_spec.rb",
    "spec/schema.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.0.1"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.0.1"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.0.1"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

